Provide timeout to aggregate responses Manage asynchronous events correctly Added debug message support

diff --git a/debug/org.eclipse.ptp.debug.sdm/configure b/debug/org.eclipse.ptp.debug.sdm/configure
--- a/debug/org.eclipse.ptp.debug.sdm/configure
+++ b/debug/org.eclipse.ptp.debug.sdm/configure
@@ -464,7 +464,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all bitvector libaif ../org.eclipse.ptp.proxy ../org.eclipse.ptp.utils"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar build build_cpu build_vendor build_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE RANLIB ac_ct_RANLIB host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL PTPDBGJNI_TRUE PTPDBGJNI_FALSE LIBOBJS OMPI_INFO MPIRUN subdirs LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar build build_cpu build_vendor build_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE RANLIB ac_ct_RANLIB host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL PTPDBGJNI_TRUE PTPDBGJNI_FALSE LIBOBJS OMPI_INFO subdirs LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -21184,60 +21184,14 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-if test "$ac_cv_path_OMPI_INFO" != no; then
-	# Extract the first word of "mpirun", so it can be a program name with args.
-set dummy mpirun; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_MPIRUN+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $MPIRUN in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_MPIRUN="$MPIRUN" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_MPIRUN="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-  test -z "$ac_cv_path_MPIRUN" && ac_cv_path_MPIRUN="no"
-  ;;
-esac
-fi
-MPIRUN=$ac_cv_path_MPIRUN
-
-if test -n "$MPIRUN"; then
-  echo "$as_me:$LINENO: result: $MPIRUN" >&5
-echo "${ECHO_T}$MPIRUN" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
+if test "$ac_cv_path_OMPI_INFO" = no; then
+	{ { echo "$as_me:$LINENO: error: SDM currently requires Open MPI to be installed." >&5
+echo "$as_me: error: SDM currently requires Open MPI to be installed." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
-	if test "$ac_cv_path_MPIRUN" != no ; then
-
-cat >>confdefs.h <<\_ACEOF
-#define OMPI 1
-_ACEOF
 
 
-cat >>confdefs.h <<_ACEOF
-#define MPIRUN "$ac_cv_path_MPIRUN"
-_ACEOF
-
-	fi
-fi
 
           ac_config_files="$ac_config_files Makefile"
 
@@ -21965,7 +21919,6 @@ s,@PTPDBGJNI_TRUE@,$PTPDBGJNI_TRUE,;t t
 s,@PTPDBGJNI_FALSE@,$PTPDBGJNI_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@OMPI_INFO@,$OMPI_INFO,;t t
-s,@MPIRUN@,$MPIRUN,;t t
 s,@subdirs@,$subdirs,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
