Add option to disable x10 support

diff --git a/debug/org.eclipse.ptp.debug.sdm/configure b/debug/org.eclipse.ptp.debug.sdm/configure
--- a/debug/org.eclipse.ptp.debug.sdm/configure
+++ b/debug/org.eclipse.ptp.debug.sdm/configure
@@ -699,6 +699,8 @@ CPP
 GREP
 EGREP
 LIBOBJS
+X10_BACKEND_TRUE
+X10_BACKEND_FALSE
 subdirs
 LTLIBOBJS'
 ac_subst_files=''
@@ -1291,6 +1293,7 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
+  --disable-x10           Disable x10 support (default is no)
 
 Some influential environment variables:
   CC          C compiler command
@@ -5719,10 +5722,31 @@ fi
 done
 
 
+# Check whether --enable-x10 was given.
+if test "${enable_x10+set}" = set; then
+  enableval=$enable_x10; case "${enableval}" in
+       yes) X10_BACKEND=1 ;;
+       no)  X10_BACKEND=0 ;;
+       *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --disable-x10" >&5
+echo "$as_me: error: bad value ${enableval} for --disable-x10" >&2;}
+   { (exit 1); exit 1; }; } ;;
+	esac
+else
+  X10_BACKEND=1
+fi
 
-cat >>confdefs.h <<\_ACEOF
-#define X10_BACKEND 1
+
+cat >>confdefs.h <<_ACEOF
+#define X10_BACKEND $X10_BACKEND
 _ACEOF
+
+ if test "$X10_BACKEND" = 1; then
+  X10_BACKEND_TRUE=
+  X10_BACKEND_FALSE='#'
+else
+  X10_BACKEND_TRUE='#'
+  X10_BACKEND_FALSE=
+fi
 
 
 
@@ -5839,6 +5863,13 @@ if test -z "${am__fastdepCC_TRUE}" && test -z "${am__fastdepCC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${X10_BACKEND_TRUE}" && test -z "${X10_BACKEND_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"X10_BACKEND\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"X10_BACKEND\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -6460,11 +6491,13 @@ CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
+X10_BACKEND_TRUE!$X10_BACKEND_TRUE$ac_delim
+X10_BACKEND_FALSE!$X10_BACKEND_FALSE$ac_delim
 subdirs!$subdirs$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 88; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 90; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
