Changed error message.

diff --git a/rms/org.eclipse.ptp.rm.orte.proxy/configure b/rms/org.eclipse.ptp.rm.orte.proxy/configure
--- a/rms/org.eclipse.ptp.rm.orte.proxy/configure
+++ b/rms/org.eclipse.ptp.rm.orte.proxy/configure
@@ -4286,8 +4286,8 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 else
-	{ { echo "$as_me:$LINENO: error: You must install Open MPI first." >&5
-echo "$as_me: error: You must install Open MPI first." >&2;}
+	{ { echo "$as_me:$LINENO: error: Open MPI not installed, skipping..." >&5
+echo "$as_me: error: Open MPI not installed, skipping..." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
